const EMPTY = [];

const SMALL = [
  {
    id: "1",
    imageSource: "/images/burger1.png",
    title: "Burger 1",
    price: 5.297,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "2",
    imageSource: "/images/burger2.png",
    title: "Burger 2",
    price: 7.556,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
];

const MEDIUM = [
  {
    id: "1",
    imageSource: "/images/burger-bacon-egg.png",
    title: "Burger Smoke BBQ",
    price: 5.598,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "2",
    imageSource: "/images/burger-vegan.png",
    title: "Vegan Burger",
    price: 5.4985,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "3",
    imageSource: "/images/burger3.png",
    title: "Burger poulet",
    price: 5.367,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "4",
    imageSource: "/images/drink1.png",
    title: "Coke 25cl",
    price: 3.568,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "5",
    imageSource: "/images/drink2.png",
    title: "Pepsi 25cl",
    price: 3.487,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
];

const LARGE = [
  {
    id: "1",
    imageSource: "/images/burger4.png",
    title: "Burger Smoke BBQ",
    price: 5.598,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "2",
    imageSource: "/images/burger7.png",
    title: "Crazee Burger",
    price: 12.568,
    quantity: 0,
    isAvailable: true,
    isAdvertised: true,
  },

  {
    id: "3",
    imageSource: "/images/burger5.png",
    title: "Double Cheese Burger",
    price: 4.167,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "4",
    imageSource: "/images/burger9.png",
    title: "Vegan Burger",
    price: 5.4985,
    quantity: 0,
    isAvailable: false,
    isAdvertised: true,
  },

  {
    id: "5",
    imageSource: "/images/burger3.png",
    title: "Fishee Burger",
    price: 4.487,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "6",
    imageSource: "/images/fries3.png",
    title: "French Fries",
    price: 3.356,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "7",
    imageSource: "/images/burger6.png",
    title: "South Burger",
    price: 4.567,
    quantity: 0,
    isAvailable: true,
    isAdvertised: true,
  },
  {
    id: "8",
    imageSource: "/images/burger12.png",
    title: "Chicken Burger",
    price: 4.1678,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "9",
    imageSource: "/images/burger11.png",
    title: "Mexican Burger",
    price: 3.7,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "10",
    imageSource: "/images/burger2.png",
    title: "Classic",
    price: 3.378,
    quantity: 0,
    isAvailable: true,
    isAdvertised: true,
  },
];

export const fakeMenu = {
  EMPTY,
  SMALL,
  MEDIUM,
  LARGE,
};
